export const DISPLAY_ALERT = 'DISPLAY_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN';
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR';

export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN';

export const LOGOUT_USER = 'LOGOUT_USER';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';

export const START_EXAM_BEGIN = 'START_EXAM_BEGIN';
export const START_EXAM_SUCCESS = 'START_EXAM_SUCCESS';

export const FINISH_EXAM_ACTION = 'FINISH_EXAM_ACTION';

export const RESTART_EXAM_ACTION = 'RESTART_EXAM_ACTION';

export const MOVE_NEXT_ACTION = 'MOVE_NEXT_ACTION';
export const MOVE_PREV_ACTION = 'MOVE_PREV_ACTION';

export const SET_USER_ID = 'SET_USER_ID';

export const SET_RESULT_ACTION = 'SET_RESULT_ACTION_BEGIN';

export const UPDATE_RESULT_ACTION = 'UPDATE_RESULT_ACTION';

export const SET_CHECK_ANSWER = 'SET_CHECK_ANSWER';
export const SET_UNCHECK_ANSWER = 'SET_UNCHECK_ANSWER';
